// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUTsQzVwqQqMgbqg6nsCHsJU0pRuIf3IE',
    appId: '1:323881496938:web:3e478ceae1029996f07513',
    messagingSenderId: '323881496938',
    projectId: 'gestor-escolar-app',
    authDomain: 'gestor-escolar-app.firebaseapp.com',
    databaseURL: 'https://gestor-escolar-app-default-rtdb.firebaseio.com',
    storageBucket: 'gestor-escolar-app.firebasestorage.app',
    measurementId: 'G-89FQD44EWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjw7UoGnrSGMzqs_XbNo8cgHxc7vecSKk',
    appId: '1:323881496938:android:f4a63dd23cd92d6bf07513',
    messagingSenderId: '323881496938',
    projectId: 'gestor-escolar-app',
    databaseURL: 'https://gestor-escolar-app-default-rtdb.firebaseio.com',
    storageBucket: 'gestor-escolar-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWjg2VnmLke7ioUHPvb7RHHKU5mCttiNw',
    appId: '1:323881496938:ios:c543ed793a062474f07513',
    messagingSenderId: '323881496938',
    projectId: 'gestor-escolar-app',
    databaseURL: 'https://gestor-escolar-app-default-rtdb.firebaseio.com',
    storageBucket: 'gestor-escolar-app.firebasestorage.app',
    iosBundleId: 'com.alexrangel.gestorEscolarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWjg2VnmLke7ioUHPvb7RHHKU5mCttiNw',
    appId: '1:323881496938:ios:c543ed793a062474f07513',
    messagingSenderId: '323881496938',
    projectId: 'gestor-escolar-app',
    databaseURL: 'https://gestor-escolar-app-default-rtdb.firebaseio.com',
    storageBucket: 'gestor-escolar-app.firebasestorage.app',
    iosBundleId: 'com.alexrangel.gestorEscolarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUTsQzVwqQqMgbqg6nsCHsJU0pRuIf3IE',
    appId: '1:323881496938:web:994cdb453f4e7106f07513',
    messagingSenderId: '323881496938',
    projectId: 'gestor-escolar-app',
    authDomain: 'gestor-escolar-app.firebaseapp.com',
    databaseURL: 'https://gestor-escolar-app-default-rtdb.firebaseio.com',
    storageBucket: 'gestor-escolar-app.firebasestorage.app',
    measurementId: 'G-DQY92KZMVT',
  );

}